export default [
  {
    name:'个人项目仓库情况',
    startTime:'2016-7',
    endTime:'至今',
    des:`<a href="https://github.com/MyButifullyLife">https://github.com/MyButifullyLife</a>  个人GitHub地址,  在公司用公司私有仓库，因参与过多项目选择其中几个进行介绍。`,
    img:[
      require('../assets/images/me/1.jpg'),
      require('../assets/images/me/2.jpg'),
      require('../assets/images/me/3.jpg'),
      require('../assets/images/me/4.jpg'),
    ]
  },
  {
    name:'营销通2.0',
    startTime:'2018-6',
    endTime:'2019-5',
    des:'此项目为移动端项目，为了方便各级人员随时随地查看权限范围内的销售数据，因此推出了营销通2.0',
    img:[
      require('../assets/images/newMarketing/1.jpg'),
      require('../assets/images/newMarketing/2.jpg'),
      require('../assets/images/newMarketing/3.jpg'),
      require('../assets/images/newMarketing/4.jpg'),
      require('../assets/images/newMarketing/5.jpg'),
      require('../assets/images/newMarketing/6.jpg'),
      require('../assets/images/newMarketing/7.jpg'),
    ]
  },
  {
    name:'MSCP',
    startTime:'2018-8',
    endTime:'2019-4',
    des:'解决各个美的各个事业部 采购人员只能在PC端录入和查询的痛点，因此推出可随时随地录入和查询操作的移动端MSCP系统。',
    img:[
      require('../assets/images/mscp/mscp-1.jpg'),
      require('../assets/images/mscp/mscp-2.jpg'),
      require('../assets/images/mscp/mscp-3.jpg'),
      require('../assets/images/mscp/mscp-4.jpg'),
      require('../assets/images/mscp/mscp-5.jpg'),
    ]
  },
  {
    name:'物流配送交付',
    startTime:'2018-10',
    endTime:'2019-5',
    des:'方便物料配送司机可以随时预约到最近厂区卸货，并可查看产区卸货区等待时间和车位情况合理分配送货时间',
    img:[
      require('../assets/images/logistics/1.png'),
      require('../assets/images/logistics/2.png'),
      require('../assets/images/logistics/3.png'),
      require('../assets/images/logistics/4.png'),
      require('../assets/images/logistics/5.png'),
      require('../assets/images/logistics/6.png'),
    ]
  },
  {
    name:'Iot区域大屏',
    startTime:'2018-1',
    endTime:'2018-2',
    des:'在Iot年会上用于展示区域数据展示   项目在线地址-PC端打开 <a href="http://bigdataservice.midea.com/iot_smart/#/">http://bigdataservice.midea.com/iot_smart/#/</a>',
    img:[
      require('../assets/images/bigWindow/1.jpg'),
    ]
  },
  {
    name:'EAM设备维护',
    startTime:'2018-4',
    endTime:'2019-1',
    des:'解决美的各事业部工厂工人在维护设备的时候每次只能手写记下，然后再经过pc对设备信息录入和提交故障， 严重影响工作效率， 因此推出了移动版的设备维护，让工人可以即时上报设备信息和派工等操作，提高工作效率',
    img:[
      require('../assets/images/eam/1.jpg'),
      require('../assets/images/eam/2.jpg'),
      require('../assets/images/eam/3.jpg'),
      require('../assets/images/eam/4.jpg'),
      require('../assets/images/eam/5.jpg'),
    ]
  },
  {
    name:'启明星',
    startTime:'2017-10',
    endTime:'2018-1',
    des:'洗衣机事业部管理应用入口，可以查看洗衣机事业部财务数据，方便总部人员进行预警操作。',
    img:[
      require('../assets/images/enlightenmentStar/1.jpg'),
      require('../assets/images/enlightenmentStar/2.jpg'),
      require('../assets/images/enlightenmentStar/3.jpg'),
      require('../assets/images/enlightenmentStar/4.jpg'),
      require('../assets/images/enlightenmentStar/5.jpg'),
      require('../assets/images/enlightenmentStar/6.jpg'),
    ]
  },
  {
    name:'魔力方块',
    startTime:'2017-10',
    endTime:'2018-1',
    des:'<a href="http://weixincs.midea.com/apps//wx-game-template/magicsquare/index.html#!/">点击前往</a> 基于微信小游戏刷爆朋友圈推广效应来推广产品。 为此目的在原来游戏管理平台上新增 魔力方块游戏，次游戏与以往不同， 游戏皮肤和奖品 管理者可以随意跟改，例如圣诞节可以跟改圣诞主题风格！ 次游戏类似于 踩黑白格',
    img:[
      require('../assets/images/magicBox/1.jpg'),
      require('../assets/images/magicBox/2.jpg'),
      require('../assets/images/magicBox/3.jpg'),

    ]
  }
]
